// Writes src/asset-stamps.ts from the real bytes of every asset a browser is
// told to cache for a long time. Filenames stay stable (embeds and the plugin
// point at /player/player.js), so the cache key is a ?v= content hash instead:
// change the file and every page asks for a new URL on the next deploy.
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const ASSETS = [
  '/styles.css',
  '/fonts/fonts.css',
  '/player/player.css',
  '/player/player.js',
  '/app.js',
  '/admin.js',
  '/page.js',
  '/playlist.js',
  '/hills.js',
  '/embed.js',
];

const stamps = {};
for (const path of ASSETS) {
  const bytes = await readFile(join(root, 'public', path));
  stamps[path] = createHash('sha256').update(bytes).digest('hex').slice(0, 10);
}

const body = `// Generated by scripts/asset-stamp.mjs on deploy. Do not edit by hand.
export const ASSET_STAMPS: Record<string, string> = ${JSON.stringify(stamps, null, 2)
  .replace(/"([^"]+)":/g, "'$1':")
  .replace(/"/g, "'")
  .replace(/'(\s*)}$/, "',$1}")};
`;

const out = join(root, 'src', 'asset-stamps.ts');
const current = await readFile(out, 'utf8').catch(() => '');
if (current !== body) {
  await writeFile(out, body);
  console.log('asset-stamp: updated src/asset-stamps.ts');
} else {
  console.log('asset-stamp: unchanged');
}
