// Generated by scripts/asset-stamp.mjs on deploy. Do not edit by hand.
export const ASSET_STAMPS: Record<string, string> = {
  '/styles.css': 'c31c48dbf6',
  '/landing.css': 'eb93c380f9',
  '/landing.js': '350ae46818',
  '/fonts/fonts.css': '5a6b738f06',
  '/player/player.css': '94419afd77',
  '/player/player.js': 'c64a20c647',
  '/app.js': 'bf80a354f8',
  '/admin.js': '9a591505db',
  '/page.js': '0c5296da7f',
  '/playlist.js': '8ddeb7a1df',
  '/hills.js': '08ebc02b29',
  '/embed.js': 'cb11a4e521',
};
