// Generated by scripts/asset-stamp.mjs on deploy. Do not edit by hand.
export const ASSET_STAMPS: Record<string, string> = {
  '/styles.css': 'c31c48dbf6',
  '/landing.css': 'eb93c380f9',
  '/landing.js': '350ae46818',
  '/fonts/fonts.css': '5a6b738f06',
  '/player/player.css': '06a1887a03',
  '/player/player.js': 'bba2b93a6e',
  '/app.js': 'a911983d4f',
  '/admin.js': '9a591505db',
  '/page.js': '0c5296da7f',
  '/playlist.js': '8ddeb7a1df',
  '/hills.js': '08ebc02b29',
  '/embed.js': 'cb11a4e521',
};
