// Generated by scripts/asset-stamp.mjs on deploy. Do not edit by hand.
export const ASSET_STAMPS: Record<string, string> = {
  '/styles.css': 'c31c48dbf6',
  '/landing.css': 'c50fc7553a',
  '/landing.js': 'd96f688c08',
  '/fonts/fonts.css': 'fa1c4ded89',
  '/player/player.css': '94419afd77',
  '/player/player.js': 'd95c87e19e',
  '/app.js': 'fa63bf1a99',
  '/admin.js': '9a591505db',
  '/page.js': '0c5296da7f',
  '/playlist.js': '8ddeb7a1df',
  '/hills.js': '08ebc02b29',
  '/embed.js': 'cb11a4e521',
};
